"""
Installs the Formula1 typefaces into the site.

Usage (from the repo root):
    python3 tools/install_f1_fonts.py ~/Downloads/formula1-fonts.zip    # or a folder of .ttf/.otf files

Finds the Regular, Bold, Black, Italic and Wide cuts by file name, converts each to WOFF2 in
assets/fonts/, and rewrites assets/fonts/f1.css so the site switches its display and text
tokens over to the Formula1 family. Needs fonttools + brotli (pip install fonttools brotli).
"""
import io, os, re, sys, zipfile
from fontTools.ttLib import TTFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'assets', 'fonts')

# (pattern on the file name, family, weight, style, output name) — first match wins per output.
CUTS = [
    (r'wide', 'Formula1 Wide', 700, 'normal', 'Formula1-Wide'),
    (r'black', 'Formula1', 900, 'normal', 'Formula1-Black'),
    (r'bold', 'Formula1', 700, 'normal', 'Formula1-Bold'),
    (r'italic', 'Formula1', 400, 'italic', 'Formula1-Italic'),
    (r'regular|display-?regular|book', 'Formula1', 400, 'normal', 'Formula1-Regular'),
]


def sources(path):
    if zipfile.is_zipfile(path):
        with zipfile.ZipFile(path) as z:
            for n in z.namelist():
                if n.lower().endswith(('.ttf', '.otf', '.woff', '.woff2')) and '__MACOSX' not in n:
                    yield os.path.basename(n), io.BytesIO(z.read(n))
    else:
        for dp, _, fs in os.walk(path):
            for f in fs:
                if f.lower().endswith(('.ttf', '.otf', '.woff', '.woff2')):
                    yield f, open(os.path.join(dp, f), 'rb')


def main(src):
    os.makedirs(OUT, exist_ok=True)
    done = {}
    for name, fh in sources(os.path.expanduser(src)):
        low = name.lower()
        if 'formula' not in low and 'f1' not in low:
            continue
        for pat, fam, wt, st, out in CUTS:
            if out in done or not re.search(pat, low):
                continue
            font = TTFont(fh)
            font.flavor = 'woff2'
            font.save(os.path.join(OUT, out + '.woff2'))
            done[out] = (fam, wt, st)
            print(f'{name} -> assets/fonts/{out}.woff2')
            break
    if not done:
        sys.exit('No Formula1 font files found in ' + src)

    faces = ''.join(
        f"@font-face {{ font-family: '{fam}'; src: url('{out}.woff2') format('woff2'); "
        f"font-weight: {wt}; font-style: {st}; font-display: swap; }}\n"
        for out, (fam, wt, st) in done.items())
    display = "'Formula1 Wide'" if 'Formula1-Wide' in done else "'Formula1'"
    tokens = (":root {\n"
              f"  --display: {display}, 'Anybody', sans-serif;\n"
              "  --text: 'Formula1', 'Barlow', sans-serif;\n"
              f"  --display-style: {'italic' if 'Formula1-Italic' in done and 'Formula1-Wide' not in done else 'normal'};\n"
              "}\n")
    with open(os.path.join(OUT, 'f1.css'), 'w') as f:
        f.write('/* Formula1 typefaces — generated by tools/install_f1_fonts.py. */\n' + faces + tokens)
    print('Wrote assets/fonts/f1.css with', len(done), 'faces')


if __name__ == '__main__':
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    main(sys.argv[1])
